### ISSUE TITLE
Create a method which produces a report "Capital cities in the region ordered by largest population to smallest"

### ISSUE THREAD

**Issue by rowanwhitton** [m0nicarichards0n/sem-group-d#51]

**Comment by rowanwhitton** [comment]
As a user, I want to be able to sort the capital cities of regions from largest to smallest population so that I can easily view the largest population of capital cities in regions.

**Comment by m0nicarichards0n** [comment]
PR: https://github.com/m0nicarichards0n/sem-group-d/pull/90
