### ISSUE TITLE
Create a method which produces a report "Cities in the world ordered by largest population to smallest"

### ISSUE THREAD

**Issue by rowanwhitton** [m0nicarichards0n/sem-group-d#52]

**Comment by rowanwhitton** [comment]
As a user, I want to be able to sort the cities of the world by largest to smallest population so that I can easily view the largest population of cities in the world.

**Comment by m0nicarichards0n** [comment]
PR up for review: https://github.com/m0nicarichards0n/sem-group-d/pull/83
