### ISSUE TITLE
Create a method which produces a report of  "The population in cities / not in cities in the Continent"

### ISSUE THREAD

**Issue by rowanwhitton** [m0nicarichards0n/sem-group-d#62]

**Comment by rowanwhitton** [comment]
As a user, I want to be able to see the number of people living in cities and not living in cities for each continent so that I can compare the two values and compare the continents.

**Comment by m0nicarichards0n** [comment]
PR: https://github.com/m0nicarichards0n/sem-group-d/pull/91
